### ISSUE TITLE
OneXPlayer Intel Gamepad 

### ISSUE THREAD

**Issue by ruineka** [theVakhovskeIsTaken/holoiso_install_main#1]
The AMD OneXPlayer has a different device ID that just works out of the box, but the Intel variants use a different ID which a udev can fix.

I took a line from my script to automate setting up Pop OS on the OneXPlayer which will simply download a udev adding the ID necessary for xpad.

sudo curl -o /etc/udev/rules.d/99-oxpgamepad.rules https://pastebin.com/raw/WuB44000

**Comment by theVakhovskeIsTaken** [comment]
Added as https://github.com/theVakhovskeIsTaken/holoiso_install_main/commit/30e4006b7dd23b17a333c3d3a73454e0cbbbcdba
